GP_DJ/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from video_games.views import pageNotFound

urlpatterns = [
      path('admin/', admin.site.urls),
      path('', include('video_games.urls')),
      path('captcha/', include('captcha.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
      import debug_toolbar
      urlpatterns = [
            path('__debug__/', include(debug_toolbar.urls)),
      ] + urlpatterns

handler404 = pageNotFound

video_games/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import *

app_name = 'video_games'

urlpatterns = [
    path('', IndexListView.as_view(), name='index'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    #path('', cache_page(60)(IndexListView.as_view()), name='index'),
    path('game/all/', GameListView.as_view(), name='game-list'),
    path('game/<slug:slug>/', GameDetailView.as_view(), name='game-detail'),
    path('genre/all/', GenreListView.as_view(), name='genre-list'),
    path('genre/<int:pk>/', GenreDetailView.as_view(), name='genre-detail'),
    path('platform/all/', PlatformListView.as_view(), name='platform-list'),
    path('platform/<int:pk>/', PlatformDetailView.as_view(), name='platform-detail'),
    path('user/register/', RegisterUser.as_view(), name='register'),
    path('page/login/', LoginUser.as_view(), name='login-page'),
    path('user/logout/', user_logout, name='user-logout'),
    path('search/', search, name='search'),
    path('add/comment/', add_comment, name='add-comment'),
    path('fav/change/<int:pk>/', change_fav_status, name='fav-status'),
    path('api/v1/gamelist', GameListAPIView.as_view()),
    path('settings/', settings, name='settings'),
    path('add/game/', AddGame.as_view(), name='add-game'),
    path('add/platform/', AddPlatform.as_view(), name='add-platform'),
    path('add/genre/', AddGenre.as_view(), name='add-genre'),
    path('add/developer/', add_developer, name='add-developer'),
]

video_games/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Platform(models.Model):
    type = models.CharField(max_length=24, verbose_name='Тип')
    logo = models.ImageField(upload_to='video_games_platform_logo/', null=True, blank=True)
    about = models.TextField(blank=True, null=True)
    # game

    def __str__(self):
        return self.type

    def get_absolute_url(self):
        return reverse('video_games:platform-detail', kwargs={'pk': self.id})

    class Meta:  # для русификации в админ панели
        verbose_name = 'Платформа'
        verbose_name_plural = 'Платформы'
        ordering = ['type']


class Genre(models.Model):
    name = models.CharField(max_length=24)
    logo = models.ImageField(upload_to='video_games_genre_logo/', null=True, blank=True)

    # game

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('video_games:genre-detail', kwargs={'pk': self.id})


class Developer(models.Model):
    name = models.CharField(max_length=24)
    logo = models.ImageField(upload_to='video_games_dev_logo/', null=True, blank=True)

    def __str__(self):
        return self.name


class Game(models.Model):
    name = models.CharField(max_length=128)
    year = models.IntegerField(default=0)
    rating = models.FloatField(default=5.0)
    views = models.IntegerField(default=0)
    poster = models.ImageField(upload_to='video_games_posters/', null=True, blank=True)
    plot = models.FileField(upload_to='video_games_plots/', null=True, blank=True)
    trailer = models.CharField(max_length=11, null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)
    platform = models.ForeignKey(Platform, related_name='game', on_delete=models.SET_NULL,
                                 null=True, blank=True)
    developer = models.ForeignKey(Developer, related_name='game', on_delete=models.SET_NULL,
                                  null=True, blank=True)
    genre = models.ManyToManyField(Genre, related_name='game', blank=True)
    fans = models.ManyToManyField(User, related_name='favs', blank=True)
    # comments

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('video_games:game-detail', kwargs={'slug': self.slug})


class Addon(models.Model):
    user = models.OneToOneField(User, related_name='addon', on_delete=models.CASCADE)
    ava = models.ImageField(upload_to='video_games_avas/')

    def __str__(self):
        return f'{self.user}'

    def get_absolute_url(self):
        return reverse('video_games:author', kwargs={'pk': self.user.id})


class Comment(models.Model):
    text = models.TextField()
    author = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE)
    game = models.ForeignKey(Game, related_name='comments', on_delete=models.CASCADE)
    published = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['-published']

video_games/forms.py
from captcha.fields import CaptchaField
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from .models import *


class GameForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['platform'].empty_label = 'Платформа не выбрана'
        self.fields['developer'].empty_label = 'Разработчик не выбран'

    class Meta:
        model = Game
        exclude = ['views', 'slug', 'fans']

    def clean_name(self): # собственный валидатор
        name = self.cleaned_data['name']
        if 'qarasuv' == name:
            raise ValidationError('Название не должно содержать имя \'qarasuv\'')
        return name

class PlatformForm(ModelForm):
    class Meta:
        model = Platform
        fields = '__all__' # все поля кроме автоматических


class GenreForm(ModelForm):
    class Meta:
        model = Genre
        fields = '__all__'


class DeveloperForm(ModelForm):
    class Meta:
        model = Developer
        fields = '__all__'

class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input', 'placeholder': "Enter your login"}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': "Enter your Password"}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input', 'placeholder': "Return your Password"}))

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input', 'placeholder': "Enter your login"}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

class ContactForm(forms.Form):
    name = forms.CharField(label='Имя', max_length=255)
    email = forms.EmailField(label='Email')
    content = forms.CharField(widget=forms.Textarea(attrs={'cols': 60, 'rows': 10, 'placeholder': "Оставьте ваши пожелания!"}))
    captcha = CaptchaField()

video_games/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.views import LoginView
from django.core.cache import cache
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, FormView
from rest_framework import generics
from .serializers import *
from .forms import *
from .utils import DataMixin


class IndexListView(ListView):
    model = Game
    template_name = 'video_games/index.html'
    queryset = Game.objects.order_by('-rating')[:8].select_related('platform')
    context_object_name = 'best_games'


class GameListView(ListView):
    paginate_by = 5
    model = Game
    queryset = Game.objects.order_by('year').select_related('platform')
    context_object_name = 'all_games'  # имя в шаблоне ( по умолчанию object_list )


class GameDetailView(DetailView):
    model = Game
    queryset = Game.objects.select_related('platform', 'developer')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # comments = cache.get('comments')
        # if not comments:
        context["comments_list"] = Game.objects.get(slug=self.kwargs['slug']).comments.all().select_related('author', 'author__addon')
        # cache.set('comments', comments, 60)
        return context

    def get_object(self, queryset=None):
        game = super(GameDetailView, self).get_object(queryset=queryset)
        game.views += 1
        game.save()
        return game


class GenreListView(ListView):
    model = Genre
    context_object_name = 'genres'
    queryset = Genre.objects.all().prefetch_related('game')


class GenreDetailView(DetailView):
    model = Genre
    extra_context = {
        'genres_all': Genre.objects.all(),
    }


class PlatformListView(ListView):
    model = Platform
    context_object_name = 'platforms'


class PlatformDetailView(DetailView):
    model = Platform


def user_logout(request):
    logout(request)
    return redirect('video_games:login-page')


def search(request):
    match = request.POST.get('match')
    if match:
        games = Game.objects.filter(name__icontains=match).prefetch_related('genre')
        context = {
            'match': match,
            'games': games,
        }
        return render(request, template_name='video_games/search.html',
                      context=context)
    else:
        return redirect('video_games:index')


def add_comment(request):
    text = request.POST.get('text')
    author = request.user
    game_id = request.POST.get('post_id')
    game = Game.objects.get(pk=game_id)
    if text and author:
        new_comment = Comment(text=text, author=author, game=game)
        new_comment.save()
    return HttpResponseRedirect(game.get_absolute_url())


def change_fav_status(request, pk):
    user = request.user
    game = Game.objects.get(pk=pk)
    if user in game.fans.all():
        game.fans.remove(user)
    else:
        game.fans.add(user)
    return HttpResponseRedirect(game.get_absolute_url())


class GameListAPIView(generics.ListAPIView):
    serializer_class = GameSerializer1
    queryset = Game.objects.order_by('name')


def settings(request):
    context = {
        'gf': GameForm(),
        'pf': PlatformForm(),
        'gef': GenreForm(),
        'df': DeveloperForm(),
    }
    return render(request, template_name='video_games/settings.html', context=context)


class AddGame(CreateView):
    form_class = GameForm


class AddPlatform(CreateView):
    form_class = PlatformForm


class AddGenre(CreateView):
    form_class = GenreForm
    # success_url = reverse_lazy('video_games:genre-list')


def add_developer(request):
    form = DeveloperForm(request.POST, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('video_games:index')
    else:
        return redirect('video_games:settings')


def pageNotFound(request, exception):  # срабатывает при ошибке 404
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'video_games/register.html'
    success_url = reverse_lazy('video_games:login-page')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('video_games:index')


class LoginUser(DataMixin, LoginView):
    form_class = AuthenticationForm
    template_name = 'video_games/login.html'

    def get_success_url(self):
        return reverse_lazy("video_games:index")


class ContactFormView(DataMixin, FormView):
    form_class = ContactForm
    template_name = 'video_games/contacts.html'
    success_url = reverse_lazy('video_games:index')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return context  # dict(list(context.items()) + list(c_def.items()))

    def form_valid(self, form):
        print(form.cleaned_data)
        return redirect('video_games:index')

video_games/templates/video_games/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'video_games/img/vg.png' %}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'video_games/css/style.css' %}">
  </head>
<body class="bg-dark">
      <nav class="navbar navbar-expand-lg bg-light">
        <div class="container">
          <a class="navbar-brand" href="{% url 'video_games:index' %}">
            <img src="{% static 'video_games/img/vg.png' %} " width="80">
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'video_games:game-list' %}">All Games</a>
              </li>

              <li class="nav-item dropdown">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'video_games:genre-list' %}">Genre</a>
                </li>

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'video_games:platform-list' %}">Platform</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'video_games:contact' %}">Feedback</a>
              </li>
              
            </ul>
            <form action="{% url 'video_games:search' %} " method="post" class="d-flex" role="search">
              {% csrf_token %}
              <input class="form-control me-2" type="text" name="match" placeholder="Search" > 
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
          <div class="mx-5">
            {% if user.is_authenticated %}
            <img src="{{ user.addon.ava.url }}" width="50" class="rounded-circle">
            <a href="#" class="text-decoration-none text-dark">
                {{ user }}
            </a>
            <br>
            <a href="{% url 'video_games:user-logout' %}" class="text-decoration-none text-dark">log out</a>
            {% else %}
            <a href="{% url 'video_games:register' %}" class="text-decoration-none text-dark">Register</a>
            <a href="{% url 'video_games:login-page' %}" class="text-decoration-none text-dark">Log in</a>
            {% endif %}

            {% if user.is_staff %}
            <a href="{% url 'video_games:settings' %}">
                <img src="{% static 'video_games/img/settings.png' %}" width="20" ></a>
            {% endif %}
        </div>
        </div>
      </nav>
      
{% block content %}{% endblock %}
</body>
</html>

video_games/templates/video_games/contacts.html
{% extends 'video_games/base.html' %}

{% block title %}Сontacts{% endblock %}
{% block content %}


<h1 class="text-light text-center my-3">Feedback</h1>

<div class="container text-light p-3">
    <div class="row p-3  justify-content-center">
    <div class="col-7 text-secondary p-3 border border-secondary" >
    <form method="post">
    {% csrf_token %}

    <div class="form-error">{{ form.non_field_errors }}</div>

    {% for f in form %}

    <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>
        <p>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <button type="submit" class="btn btn-primary">Send</button>
    </form>
    </div>
        </div>
</div>

{% endblock %}

video_games/templates/video_games/game_detail.html
{% extends 'video_games/base.html' %}
{% load static %}
{% block title %}{{ game.name }}{% endblock %}



{% block content %}

<h1 class="text-light text-center my-3">{{ game.name }}</h1>

<div class="container">
    <div class="row my-3 justify-content-between">

        <div class="col-3">
            <code>Release Date: {{ game.year }}</code>
            <img src="{{ game.poster.url }}" class="w-100  rounded w">
            {% if user.is_authenticated %}
            <form action="{% url 'video_games:add-comment' %}" method="post" class="my-3">
                {% csrf_token %}
                <input type="text" name="text" placeholder="add comment">
                <input type="hidden" name="post_id" value="{{ game.id }}">
            </form>
            {% endif %} 
            <hr style="color: red;">
            {% if comments_list %}
                <p class="text-secondary">Comments ({{ comments_list|length }}) </p>
                {% for comment in comments_list %}
                <p class="text-light" style="font-size: 80%"> 
                    <img src="{{ comment.author.addon.ava.url }}" width="30" class="rounded-circle">
                    <code>{{ comment.author }}</code>
                    <br>
                {{ comment }}
                </p>
                <p class="text-secondary text-end" style="font-size: 80%">{{ comment.published|timesince }}</p>
                {% endfor %}

            {%  else %}
            <p class="text-secondary">no comments</p>    
            {% endif %} 
        </div>

        <div class="col-5">
            <h1 class="text-secondary ">
                <img src="{% static 'video_games/img/star.png' %}" class="rounded float-end p-2" width="50">    
                <p class="text-secondary text-end">{{ game.rating|floatformat:1 }} </p>   
            </h1>                      
            <h5 class="text-warning">Genre:</h5>          
            <p class="text-secondary my-3"> 
                {% for genre in game.genre.all %}
                    <a href="{{ genre.get_absolute_url }}" class="text-decoration-none text-light">{{ genre }},</a>
                {% endfor %}
            </p>
            <h5 class="text-warning">Platform: </h5>
            <a href="{{ game.platform.get_absolute_url }}" class="text-decoration-none  "><p class="text-light">{{ game.platform }}</p></a>
            <h5 class="text-warning">Summary: </h5>
            <code class="text-light" >{{ game.plot.read.decode }}</code>


        </div>

        <div class="col-4">
            <h1>
                {% if user.is_authenticated %}
                {% if game in user.favs.all %}
                <a href="{% url 'video_games:fav-status' game.id %}" class="text-decoration-none text-warning"><img width="55" src="{% static 'video_games/img/red_heart.png' %}" class="rounded float-start p-2" ></a>
                {% else %}
                <a href="{% url 'video_games:fav-status' game.id %}" class="text-decoration-none text-warning"><img width="55" src="{% static 'video_games/img/white_heart.png' %}" class="rounded float-start p-2"></a>
                {% endif %}
            {% endif %} 
            </h1>
            {% if game.developer.logo %}
            <img  src="{{ game.developer.logo.url }}" class="rounded float-end w-50">
            {% endif %}
            <br> <br> <br>
            <p class="text-warning ">Developer:</p>
             <p class="text-secondary">{{ game.developer }}</p>
            <br> <br>
            <code class="text-secondary">Views: {{ game.views }}</code>
            <hr style="height:2px; width:100%; border-width:0; color:red; background-color:red" class="my-3">
            <h5 class="text-warning text-center my-3">Trailer: </h5>
            <iframe width="460" height="260" class="border border-warning" src="https://www.youtube.com/embed/{{ game.trailer }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>        

        </div>

    </div>
</div>



{% endblock %}

video_games/templates/video_games/game_list.html
{% extends 'video_games/base.html' %}
{% load static %}
{% block title %}All Games{% endblock %}

{% block content %}

<h1 class="text-light text-center my-3">All Games</h1>

{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% for p in paginator.page_range %}
    {% if page_obj.number == p %}
    <li class="page-item active" aria-current="page">
      <span class="page-link">
        {{ p }}
        <span class="sr-only"></span>
      </span>
    </li>
    {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
    <li>
        <a class="page-link text-secondary" href="?page={{ p }}">{{ p }}</a>
    </li>
    {% endif %}
    {% endfor %}
  </ul>
</nav>
{% endif %}

<div class="container">
    <div class="row">
        {% for game in all_games %}
        <div class="col-2 py-3">
            {% if game.poster %}
            <img src="{{ game.poster.url }}" class="w-100 rounded " >
            {% endif %}
        </div>
        <div class="col-4 py-3 text-start">
            <a href="{{ game.get_absolute_url }}" class="text-decoration-none float-left">
                <h2 class="text-light  ">{{ game }}</h2>
            </a>    
                <p class="text-secondary">Platform: <a href="{{ game.platform.get_absolute_url }}" class="text-decoration-none text-light">{{ game.platform }}</a></p>
                <p class="text-secondary">Release Date: {{ game.year }}</p>
                <br>
            <img src="{% static 'video_games/img/star.png' %}"  width="20">
            <p class="text-secondary">{{ game.rating|floatformat:1 }}</p>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}




video_games/templates/video_games/genre_detail.html

{% extends 'video_games/base.html' %}
{% load static %}
{% block title %}{{ genre }}{% endblock %}




{% block content %}
<h1 class="text-light text-center my-3">Genre: {{ genre }}</h1>
<div class="container" >
    <hr style="height:2px; width:100%; border-width:0; color:red; background-color:red" class="my-3">
    <div class="row my-3 justify-content-between">
        <div class="col-2 border rounded my-3">
            {% for genre in genres_all.all %}
                <a href="{{ genre.get_absolute_url }}" class="text-decoration-none "><p class="text-light">{{ genre }}</p></a>
                <hr class="text-secondary">
            {% endfor %}
        </div> 

        <div class="col-8 my-3">

            <div class="row my-3 text-center">
        {% for game in genre.game.all %}
                <div class="col-2 ">
            <a href="{{ game.get_absolute_url }}" class="text-decoration-none ">
                <img src="{{ game.poster.url }}" width="100">
                <p class="text-light">{{ game.name }}</p>
            </a>                    
                </div>


        {% endfor %}                 
            </div>

        </div> 

        <div class="col-2 my-3 border rounded my-3 text-center">
            <br>
            <img src="{{ genre.logo.url }}" class="w-75">
            <br>
            <hr style="color: red;">
            <p class="text-light"> TOP-3:</p>
            {% for game in genre.game.all|slice:":3" %}
                <p class="text-secondary text-start">{{ game.name }}</p>
            {% endfor %}
        </div>                         
    </div>
</div>

{% endblock %}

video_games/templates/video_games/genre_list.html
{% extends 'video_games/base.html' %}
{% load static %}
{% block title %}All Genres{% endblock %}
{% block content %}

<h2 class="text-light text-center my-3">Video Game Genres: Everything You Need to Know</h2>

<div class="container">
    <div class="row my-3 ">
        <hr style="height:2px; width:100%; border-width:0; color:red; background-color:red" class="my-3">
            <h6 class="text-secondary mb-3">Although video game genres were once fairly clear cut, that’s simply not the case these days. There’s a growing variety of genres and sub-genres to understand, especially as game developers mix and blend different types of games in new and unexpected ways.
                That means the video-gaming landscape is constantly evolving. Studios work on tight schedules and follow trends when the opportunity arises. We’re here to help you keep up. In our game genres list, we’ll cover 10 of the most relevant video game categories today.</h6>
                <hr style="height:2px; width:100%; border-width:0; color:red; background-color:red" class="my-3">
                <h5 class="text-warning mb-3 text-center">ALL GENRES: </h5>
                <br><br>
            {% for genre in genres %}
            <div class="col-1 my-3">
            <img src="{{ genre.logo.url }}" width="100" height="100" class="rounded-circle">
            </div>
            <div class="col-3 text-start my-3">
                <p class="text-secondary">
                    <a href="{{ genre.get_absolute_url }}" class="text-decoration-none text-light">{{ genre.name }} ({{ genre.game.all|length  }})</a>
                </p>
            </div>
            {% endfor %}

        <div class="col-8"></div>
    </div>
</div>











{% endblock %}

video_games/templates/video_games/index.html
{% extends 'video_games/base.html' %}
{% load static %}
{% block title %}Best of All Time{% endblock %}



{% block content %}

<h1 class="text-light text-center my-3">Best Games of All Time</h1>
<div class="container">
    <div class="row">
        <div class="col-10">
            <div class="row my-3 ">
                {% for game in best_games %}
                <div class="col-2 py-3">
                    <img src="{{ game.poster.url }}" class="w-100  rounded ">
                </div>
                <div class="col-4 py-3 text-start">
                    <a href="{{ game.get_absolute_url }}" class="float-left">
                        <h2 class="text-light  ">{{ game }}</h2>
                    </a>    
                        <p class="text-secondary">Platform: <a href="{{ game.platform.get_absolute_url }}" class="text-light">{{ game.platform }}</a></p>
                        <p class="text-secondary">Release Date: {{ game.year }}</p>
                        
                    <img src="{% static 'video_games/img/star.png' %}"  width="20">
                    <p class="text-secondary">{{ game.rating|floatformat:1 }}</p>
                </div>
                {% endfor %}
            </div>    
        </div>

        <div class="col-2">
            <div class="row my-3 ">

            {% if user.is_authenticated and game.fans.all %}
            <p class="text-secondary my-3"> <code> My wish list:</code></p>  
            <hr style="height:2px; width:100%; border-width:0; color:red; background-color:red"  >  
            <div class="row">
                {% for game in user.favs.all %}

                <code><a href="{{ game.get_absolute_url }}" class="text-light">{{ game.name }}</a></code>
                {% endfor %}
            </div>
            
            {% endif %}
            </div>  
        </div>
    </div>
</div>

{% endblock %}

video_games/templates/video_games/settings.html
{% extends 'video_games/base.html' %}
{% load static %}
{% block title %}Settings{% endblock %}

{% block content %}


<h1 class="text-light text-center my-3">
    <img src="{% static 'video_games/img/settings.png' %}" width="40" >
    Settings WASD
</h1>

{% if user.is_staff %}
<div class="container">
    <div class="row border border-secondary p-3 justify-content-between">
        <div class="col-4 text-secondary p-2" >
            <h2 class="text-warning">Add Games</h2>
            <form action="{% url 'video_games:add-game' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    {{ gf.as_table }}
                </table>
                <input type="submit" value="Add">
            </form>
        </div>
        <div class="col-5 text-secondary p-2" >
            <h2 class="text-warning">Add Platform</h2>
            <form action="{% url 'video_games:add-platform' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    {{ pf.as_table }}
                </table>
                <input type="submit" value="Add">
            </form>
        </div>
        <div class="col-3 text-secondary p-2" >
            <h2 class="text-warning">Add Genre</h2>
            <form action="{% url 'video_games:add-genre' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    {{ gef.as_table }}
                </table>
                <input type="submit" value="Add">
            </form>
            <br><br><br>
            <h2 class="text-warning">Add Developer</h2>
            <form action="{% url 'video_games:add-developer' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    {{ df.as_table }}
                </table>
                <input type="submit" value="Add" >
            </form>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}